---
- name: backup homepi
  hosts: homepi
  vars:
    dateTimeForFiles: "{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"
    backupPath: "~/backup/homepi"
  become: true
  tasks:
    - include: tasks/backup_mosquitto.yml
    - include: tasks/backup_homegear.yml
    - include: tasks/backup_openhab.yml
    - include: tasks/backup_influx.yml
    - include: tasks/backup_grafana.yml
    - include: tasks/backup_zigbee2mqtt.yml