---
- name: Archive openhab to /tmp
  command: 'docker exec -it openhab "/bin/bash" -c "/openhab/runtime/bin/backup /openhab/userdata/backup/{{ dateTimeForFiles }}_openhab.zip"'
- name: Fetch backup file from remote
  fetch:
      src: /home/pi/docker/openhab/config/userdata/backup/{{ dateTimeForFiles }}_openhab.zip
      dest: "{{ backupPath }}"
      flat: yes
- name: delete backup file from remote
  command: rm /home/pi/docker/openhab/config/userdata/backup/{{ dateTimeForFiles }}_openhab.zip
