---
# - name: get node-blue flows
#   get_url:
#     url: http://localhost:2001/node-blue/flows
#     dest: "/tmp/{{ dateTimeForFiles }}_node-blue-flows.json"
- name: get node-red flows
  get_url:
    url: http://localhost:1880/flows
    dest: "/tmp/{{ dateTimeForFiles }}_node-red-flows.json"
- name: Fetch backup file
  fetch:
      src: "{{ item }}"
      dest: "{{ backupPath }}"
      flat: yes
  loop:
    - /tmp/{{ dateTimeForFiles }}_node-red-flows.json
    # - /tmp/{{ dateTimeForFiles }}_node-blue-flows.json
- name: delete backup file
  file: 
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/{{ dateTimeForFiles }}_node-red-flows.json
    # - /tmp/{{ dateTimeForFiles }}_node-blue-flows.json
